<a href="https://colab.research.google.com/github/Mustak-Ahamed-Ashik/Machine-learning-Basics/blob/main/01_Vectorization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
A=np.array([[23.0, 34.2, 45.0, 12.4],
            [43.2, 23.4, 54.6, 12.8],
            [34.3, 34.6, 34.9, 21.2]])

In [4]:
print(A)

[[23.  34.2 45.  12.4]
 [43.2 23.4 54.6 12.8]
 [34.3 34.6 34.9 21.2]]


In [9]:
cal=A.sum(axis=0)
print(cal)

[100.5  92.2 134.5  46.4]


In [11]:
percentage=100*A/cal.reshape(1,4)
print(percentage)

[[22.88557214 37.09327549 33.45724907 26.72413793]
 [42.98507463 25.37960954 40.59479554 27.5862069 ]
 [34.12935323 37.52711497 25.94795539 45.68965517]]
